### ISSUE TITLE
Sandbox Starter uses disabled AWS Marketplace item

### ISSUE THREAD

**Issue by rmcolbert** [AviatrixSystems/terraform-solutions#34]
The Aviatrix Metered marketplace item (https://aws.amazon.com/marketplace/pp/B086T2RVTF) has been deactivated/disabled in the AWS Marketplace making it impossible for new users to leverage the Sandbox Starter.

**Comment by jb-smoker** [comment]
Appreciate the issue. SST has been updated with #35
